export const LISTA_HEROIS_SUCCESS = "LISTA_HEROIS_SUCCESS";

export const HEROI_SUCCESS = "HEROI_SUCCESS";

export const ATUALIZA_HEROI_SUCCESS = "ATUALIZA_HEROI_SUCCESS";

export const SEARCH_HEROI_SUCCESS = "SEARCH_HEROI_SUCCESS";

export const LISTA_SERIES_SUCCESS = "LISTA_SERIES_SUCCESS";

export const RESET = "RESET";
